### ISSUE TITLE
6.1.1 cannot find docker version

### ISSUE THREAD

**Issue by Darren-Vine** [philips-labs/terraform-cloudfoundry-variant#21]
When setting the version to 6.1.1 - ERR Failed getting docker image manifest by tag: Error reading manifest v6.1.1 in registry-1.docker.io/philipslabs/cf-variant: manifest unknown: manifest unknown  Going to retry attempt: 1

Looking at the registry it seems there is no 6.1.1.

**Comment by loafoe** [comment]
Fixed with 6.1.2
